# Server Configutation
server:
  port: 8080
  servlet:
    context-path : /myapp

# Data source configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
